# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a042e84d709de06af841bad74addecf0cbb782b4c125a0ffef77c3e96d6feee4f8d9550dc5711b93a2cb496c54ebea49dc31293cc4d0a14c205135fa75e0e8eb

test:
  secret_key_base: a81273d4a2c4b06a585d2d982bcff403460eb8e4f30e6969cb5a731ce3c560ec8f87af17da7063a882a8d8a2827a37f7c7c7d0e29459b9263d67ca965f82257c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
